version: "2"
services:

  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:1.8
    ports:
      - "16686:16686"
      - "14268"

  # Zipkin
  zipkin-all-in-one:
    image: openzipkin/zipkin:2.11.12
    ports:
      - "9411:9411"

  # Collector
  otelsvc-collector:
    image: otelsvc:latest
    command: ["--config=/etc/otelsvc-collector-config.yaml", "--http-pprof-port=1777"]
    volumes:
      - ./otelsvc-collector-config.yaml:/etc/otelsvc-collector-config.yaml
    ports:
      - "55678"
      - "55680:55679"
      - "1777:1777"
      - "8888:8888" # Prometheus metrics
    depends_on:
      - jaeger-all-in-one
      - zipkin-all-in-one

  # Agent
  otelsvc-agent:
    image: otelsvc:latest
    command: ["--config=/etc/otelsvc-agent-config.yaml", "--http-pprof-port=1888"]
    volumes:
      - ./otelsvc-agent-config.yaml:/etc/otelsvc-agent-config.yaml
    ports:
      - "1888:1888"
      - "14268"
      - "55678"
      - "55679:55679"
    depends_on:
      - otelsvc-collector

  # Synthetic load generator
  synthetic-load-generator:
    image: omnition/synthetic-load-generator:1.0.25
    environment:
      - JAEGER_COLLECTOR_URL=http://otelsvc-agent:14268
    depends_on:
      - otelsvc-agent

