receivers:
  opencensus:
    endpoint: localhost:55678
  jaeger:
    protocols:
      thrift-http:
        endpoint: "localhost:14268"


exporters:
  opencensus:
    endpoint: "otel-collector:55678"
  logging:
    loglevel: debug

processors:
  batch:
  queued_retry:

extensions:
  pprof:
    endpoint: localhost:1777
  zpages:
    endpoint: localhost:55679

service:
  extensions: [pprof, zpages]
  pipelines:
    traces:
      receivers: [opencensus, jaeger]
      exporters: [opencensus, logging]
      processors: [batch, queued_retry]
    metrics:
      receivers: [opencensus]
      exporters: [logging,opencensus]

