# Enable debug level to see output of "logging" exporter
log-level: DEBUG

receivers:
  opencensus:
    endpoint: 0.0.0.0:55678

exporters:
  logging:

  zipkin:
    url: "http://zipkin-all-in-one:9411/api/v2/spans"

  jaeger-grpc:
    endpoint: jaeger-all-in-one:14250

processors:
  batch:
  queued-retry:

pipelines:
  traces:
    receivers: [opencensus]
    exporters: [logging, zipkin, jaeger-grpc]
    processors: [batch, queued-retry]
